build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
    - GO15VENDOREXPERIMENT=1
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: fieldnation/drone-s3-sync
    tag:
      - "latest"
    when:
      branch: master
